### PR TITLE
Fix build warnings for examples

### LINKED ISSUE #35: address build warnings in ncurses example
just a self-reminder.
```
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp: In function ‘void drawTopology()’:
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp:375:25: warning: variable ‘y’ set but not used [-Wunused-but-set-variable]
  375 |                     int y = 0;
      |                         ^
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp:397:25: warning: variable ‘y’ set but not used [-Wunused-but-set-variable]
  397 |                     int y = 0;
      |                         ^
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp:419:25: warning: variable ‘y’ set but not used [-Wunused-but-set-variable]
  419 |                     int y = 0;
      |                         ^
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp: In function ‘void drawRF24Pad()’:
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp:667:42: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  667 |     wprintw(rf24Pad, "RX Packets(user): %u\n", networkPacketsRX);
      |                                         ~^     ~~~~~~~~~~~~~~~~
      |                                          |     |
      |                                          |     size_t {aka long unsigned int}
      |                                          unsigned int
      |                                         %lu
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp: In function ‘void drawConnPad()’:
/home/runner/work/RF24Gateway/RF24Gateway/RF24Gateway/examples/ncurses/RF24Gateway_ncurses.cpp:714:44: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  714 |             mvwprintw(connPad, ctr++, 0, "%d %s\n", lCtr++, line.c_str());
      |                                           ~^        ~~~~~~
      |                                            |            |
      |                                            int          size_t {aka long unsigned int}
      |                                           %ld
```

### PR DESCRIPTION
**Pull request by 2bndy5**
resolves #35

### CODE REVIEW

**Comment by TMRh20** [comment]
On  https://github.com/nRF24/RF24Gateway/blob/364ab07c38107749c64b1696d55058b9e61df48a/examples/ncursesInt/RF24Gateway_ncursesInt.cpp#L203 this bit of code was intended to send a timestamp back to the sender, so I would prefer if the previous code would grab the senders address from the header and respond with a timestamp.

https://github.com/nRF24/RF24Gateway/blob/364ab07c38107749c64b1696d55058b9e61df48a/examples/ncursesInt/RF24Gateway_ncursesInt.cpp#L167  renew address should == 04444 if failure, RF24Network address on success, can you fix this while in there?

**Comment by 2bndy5** [comment]
> ```cpp
>  if ((ok = mesh.renewAddress())) 
> ```

This is a bit tricky. I'm not used to assigning a value while evaluating a condition (in C++, rust has better syntax for that). I think the requested fix would involve setting `ok` based on the `renewAddress()` result. In this instance `ok` is (supposedly) set to true if `renewAddress()` succeeds (or otherwise false), right?

**Comment by TMRh20** [comment]
> In this instance ok is (supposedly) set to true if renewAddress() succeeds (or otherwise false), right?

Yup. How about something like `ok = (mesh.renewAddress() == MESH_DEFAULT_ADDRESS) ? false : true;`

**Comment by 2bndy5** [comment]
> How about something like `ok = (mesh.renewAddress() == MESH_DEFAULT_ADDRESS) ? false : true;`

That's actually kinda redundant, `(mesh.renewAddress() != MESH_DEFAULT_ADDRESS)` would evaluate equivalently.

**Comment by TMRh20** [comment]
Hey, I'm still waking up, realized that as soon as I posted it.

**Comment by 2bndy5** [comment]
I'm not actually setup to hardware test this lib. Have you run this with the latest changes (as requested)?

**Comment by TMRh20** [comment]
Not yet, likely sometime today if all goes as planned.

**Review by TMRh20 — APPROVED** [review]
Good to go!

**Pull request merged**
